runner: "research.muP_MoE.train.train"

time: '1-00:00:00'

n_gpus: 4
cpus_per_gpu: 16

interactive_debug: false

params:
  name: muP_MoE_lr_grid_dense_fixed
  tags: ["muP_MoE", "muTransfer", "lr_grid_dense_fixed", "with_mup"]

  mup_params:
    # alpha_in: 10.0
    # alpha_out: 0.1

    alpha_in: 1.0
    alpha_out: 1.0
    base_dmodel: 64

  # training
  n_steps: 60000
  final_lr_step: 60000
  lr_warmup_steps: 600
  batch_size: 512
  cutoff: 512

  # model
  model_type: gpt
  ^dmodel: [768, 1024, 1536]
  n_blocks: 24
  dhead: 64
  attention_mode: 'vanilla'
  attention_normalization: 'dhead'
  use_torch_bmm: true

  ff_mode: vanilla
  dff_ratio: 4
  activation_type: relu

  # learning
  scheduler: cosine
  ^learning_rate: [2e-2, 1e-2, 5e-3, 2e-3, 1e-3]
  final_lr_fraction: 0.1
  grad_clip: 0.5
  weight_decay: 0.1
  init_scale: 0.1
  init_type: normal

  # FSDP
  fsdp_enabled: true
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,RoPE"

  dataset_type: c4
  mixed_precision: true
  flash_attention: true
  mixed_precision_dtype: bfloat16
  data_seed: 17

  # logging etc.
  logger_types: neptune
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 3000

  # debug
  # logger_types: "stdout"
  # n_steps: 100
  # batch_size: 8
  # cutoff: 16
  # use_dummy_dataset: true
  # n_blocks: 2
  # dmodel: 16
  # n_att_heads: 2
