
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 3b35737a38c2db680bf1325d719b5504
time: 0-05:00:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  # tags: ["projected_dis", "1ff", "dm768", "range"]
  tags: ["projected_dis", "1ff", "dm768", "COMP"]

  # ^learning_rate: [0.000125, 0.00025, 0.0005, 0.001]
  # ^learning_rate: [0.002, 0.0015]
  learning_rate: 0.0015

  dmodel: 768
  dff: 768
  # n_steps: 10_179
  # ^n_steps: [1018, 2036, 3054, 4072, 5090, 6107, 7125, 8143, 9161, 10179]
  # ^n_steps: [509, 764]
  n_steps: 10_179

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"