
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: ba8618af2f2e0bb92c5a7aaa3ba1d2a7
time: 0-03:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm256", "range", "tuned"]

  # ^learning_rate: [0.001, 0.002, 0.004] #+
  # ^learning_rate: [0.008, 0.016] #+
  # ^learning_rate: [0.0015, 0.004, 0.008] # 0.002 - 
  learning_rate: 0.004
  # ^learning_rate: [0.002, 0.003, 0.006, 0.004]
  # ^final_lr_fraction: [0.0, 0.0125, 0.025, 0.05]
  final_lr_fraction: 0.0125

  batch_size: 256
  cutoff: 256
  
  dmodel: 256
  dff: 256
  ^n_steps: [8812, 7931, 7050, 6168, 5287, 4406, 3525, 2644, 1762, 881] # 1, 0.9, 0.8, 0.7 ...
  # n_steps: 8812
