
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 916b89348a6cb0465eafe8f681ca5542
# time: 0-00:30:00
# n_gpus: 1 #dev
time: 0-01:30:00 # debug
n_gpus: 4 # debug
cpus_per_gpu: 16

params:
  name: "PD"
  # tags: ["projected_dis", "1ff", "distillation", "dm256"] 
  # tags: ["projected_dis", "1ff", "distillation", "dm256", "test"] 
  tags: ["projected_dis", "1ff", "distillation", "dm256", "tune"] 
 
  dmodel: 256
  dff: 256
  distilled_dmodel: 512
  distilled_dff: 512
  distillation_temperature: 2.0
  
  n_steps: 7050

  batch_size: 256
  # batch_size: 64 # debug
  cutoff: 256
  n_blocks: 8
  n_att_heads: 8

  scheduler: cosine
  # ^learning_rate: [asd, asd, asd, asd, asd]
  learning_rate: 0.004
  # ^lr_warmup_percent: [asd, asd, asd, asd, asd]
  lr_warmup_percent: 0.01
  # ^final_lr_fraction: [asd, asd, asd, asd, asd]
  final_lr_fraction: 0.03
 
  # [("sfkl", 0.1), ("srkl", 0.1), ("tvd", None), ("fkl", None), ("rkl", None), ("skl", 0.9)]
  distillation: True
  # ^distill_loss_type: [sfkl, srkl] 
  # ^distill_loss_type: [tvd, fkl, rkl] 
  ^distill_loss_type: [skl] 
  # ^method_lam: [0.05, 0.1, 0.2]
  # ^method_lam: [Null]
  ^method_lam: [0.8, 0.9, 0.99]
  ^kd_ratio: [0.25, 0.5, 0.75]
  distillation_temperature: 1.0 #not implemented
  # distillation_weights_path: /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-03-17_14-39-57/None/1238307/19545.pt
  distillation_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmaciejpioro/llm_random_cemetery/PD_2025-03-20_14-21-44/None/118527/19545.pt #helios

  
  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"

