
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 916b89348a6cb0465eafe8f681ca5542
time: 1-00:00:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "distillation", "dm832"] 
  # tags: ["projected_dis", "1ff", "distillation", "compression", "dm832", "range"] 
 
  dmodel: 832
  dff: 832
  distilled_dmodel: 1024
  distilled_dff: 1024
  projected_dmodel: 1024
  projected_dff: 1024

  # batch_size: 256 # dev debug
  gradient_accumulation_steps: 2

  # ^n_steps: [509, 764, 1018, 2036, 3054, 4072, 5090, 6107, 7125, 8143, 9161, 10179]
  ^n_steps: [10179]


  scheduler: cosine 
  # ^learning_rate: [0.000125]
  # ^learning_rate: [6.25e-05]
  ^learning_rate: [0.00025]
  # ^learning_rate: [0.00025, 0.0005]
  lr_warmup_percent: 0.01
  final_lr_fraction: 0.03

  # [("sfkl", 0.1), ("srkl", 0.1), ("tvd", None), ("fkl", None), ("rkl", None), ("skl", 0.9)]
  distillation: True
  ^distill_loss_type: [skl] 
  ^method_lam: [0.2]
  ^kd_ratio: [0.75]
  # ^kd_ratio: [0.5, 0.75]
  # ^distill_loss_type: [srkl] 
  # ^method_lam: [0.1]
  # ^kd_ratio: [0.5]
  distillation_temperature: 1.0 #not implemented
 
  distillation: True
  distillation_type: distilgpt
  # distillation_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-03-24_12-19-09/None/125762/15533.pt # 20
  distillation_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmaciejpioro/llm_random_cemetery/PD_2025-03-20_14-31-55/None/118538/62132.pt # helios
  # distillation_weights_path: /home/ubuntu/mstefaniak/checkpoints/dm_1024_80.pt
    
  attention_mode: projected_vanilla_res
  ff_mode: projected_vanilla_res
  projection_init_type: head_half
  projected_distillation: True
  # projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-03-24_12-19-09/None/125762/15533.pt # 20
  projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmaciejpioro/llm_random_cemetery/PD_2025-03-20_14-31-55/None/118538/62132.pt
  # projected_weights_path: /home/ubuntu/mstefaniak/checkpoints/dm_1024_80.pt

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"

