
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 3b35737a38c2db680bf1325d719b5504
time: 0-10:00:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "compression", "dm832_1024", "COMP"] 
  # tags: ["projected_dis", "1ff", "compression", "dm832_1024", "tune_lr"] 

  dmodel: 832
  dff: 832
  projected_dmodel: 1024
  projected_dff: 1024
  
  # ^learning_rate: [0.0000625, 0.000125, 0.00025]
  learning_rate: 0.000125


  # ^n_steps: [509, 764, 1018, 2036, 3054, 4072, 5090, 6107, 7125, 8143, 9161, 10179]
  n_steps: 10179

  attention_mode: projected_vanilla_rope_res
  ff_mode: projected_vanilla_res

  projection_init_type: half
 
  projected_distillation: True
  # projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmaciejpioro/llm_random_cemetery/PD_2025-03-20_14-31-55/None/118538/62132.pt # 80
  # projected_weights_path: /home/ubuntu/mstefaniak/checkpoints/dm_1024_80.pt
  projected_weights_path: /home/ubuntu/llm-random-group/llm-random-cemetery/PD_2025-05-15_12-36-06/None/10649/62132.pt # writer 80

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"

