
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 41ba87a56e92ea289913b5a7ffea8f9b
time: 0-10:00:00
# time: 0-00:50:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  # tags: ["projected_dis", "1ff", "compression", "dm256", "trapezoidal", "tune_08", "v3", "cosine"]
  # tags: ["projected_dis", "1ff", "compression", "dm768_1024", "test"] 
  # tags: ["projected_dis", "1ff", "compression", "dmx_1024", "comp_distilgpt"] 
  tags: ["projected_dis", "1ff", "compression", "dmx_1024", "comp_distilgpt", "tune"] 

  batch_size: 512

  dmodel: 512
  dff: 512
  projected_dmodel: 1024
  projected_dff: 1024
  # ^n_steps: [509, 764, 1018, 2036, 3054, 4072, 5090, 6107, 7125, 8143, 9161, 10179]
  n_steps: 20863
  
  
  # ^learning_rate: [0.0000625, 0.000125, 0.00025, 0.0005]
  # ^learning_rate: [0.000125, 0.0005]
  ^learning_rate: [0.00025]

  scheduler: cosine
  lr_warmup_percent: 0.1 #compression
  final_lr_fraction: 0.01 #compression

  # scheduler: trapezoidal
  # lr_trapezoidal_decay_fraction: 0.9 #trapezoidal
  # lr_warmup_percent: 0.02 #trapezoidal
  
  ^weight_decay: [0.01, 0.05, 0.1] # prop 10 out of
  # ^weight_decay: [0.15]
  ^grad_clip: [0.25, 0.5, 0.75, 1]
  # ^grad_clip: [0.25]


  attention_mode: projected_vanilla_res
  ff_mode: projected_vanilla_res

  projection_init_type: head_half
 
  projected_distillation: True
  # projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-03-24_12-19-09/None/125762/15533.pt # 20 helios
  # projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmaciejpioro/llm_random_cemetery/PD_2025-03-20_14-31-55/None/118537/31066.pt # 40 helios
  # projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmaciejpioro/llm_random_cemetery/PD_2025-03-20_14-31-55/None/118538/62132.pt # 80 helios
  # projected_weights_path: /home/ubuntu/mstefaniak/checkpoints/dm_1024_80.pt # writer
  projected_weights_path: /home/mstefaniak/checkpoints/dm_1024_80.pt # entropy

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"

