
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 3b35737a38c2db680bf1325d719b5504
time: 2-00:00:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm1024", "doner", "COMP2", "COMP", "rms_hln"] # , "all_head_ln", "head_ln", "rope"

  # ^learning_rate: [0.0000625, 0.000125, 0.00025, 0.0005] #+
  # ^learning_rate: [0.00075, 0.001, 0.002] # 0.0005
  # ^learning_rate: [0.00025, 0.0005, 0.001]
  # ^learning_rate: [0.0005, 0.00075]
  learning_rate: 0.001
  # ^final_lr_fraction: [0.03]
  final_lr_fraction: 0.03
  # ^lr_warmup_percent: [0.02, 0.04, 0.06]
  lr_warmup_percent: 0.01

  dmodel: 1024
  dff: 1024
  # ^n_steps: [15_533, 31_066, 62_132]  # 20T/ap
  # ^n_steps: [31_066, 62_132]
  # ^n_steps: [124_264]
  n_steps: 15_533
  # n_steps: 62_132

  # attention_mode: "rope"
  # no_positional_embedding: True
  head_layer_norm: True

  dont_save_final_model: False 
  # /home/ubuntu/llm-random-group/llm-random-cemetery/PD_2025-05-09_15-04-52
  # /home/ubuntu/llm-random-group/llm-random-cemetery/PD_2025-05-09_13-37-48

  # save_weights_path: /local_storage_1/ms_tmp/models/ #dev entropy models dir

  fsdp_use_orig_params: True
  # fsdp_enabled: False #dev
  fsdp_enabled: True #dev
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"