
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 3b35737a38c2db680bf1325d719b5504
time: 0-20:00:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm768", "COMP", "doner", "ot_4"]

  # ^learning_rate: [0.000125, 0.00025, 0.0005, 0.001]
  # ^learning_rate: [0.002, 0.0015]
  ^learning_rate: [0.0015, 0.00075]

  dmodel: 768
  dff: 768
  n_steps: 40_716
  
  dont_save_final_model: False
  # save_weights_path: /local_storage_1/ms_tmp/models/ #dev entropy models dir

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"