
parent: configs/projected_dis/4ff_large/common.yaml
md5_parent_hash: 0f5bbfd1acb29b5088f1f320eda7bea6
time: 4-00:00:00
n_gpus: 4
cpus_per_gpu: 16

params:
  name: "PD"
  # tags: ["projected_dis", "4ff", "dm960", "COMP"]
  tags: ["projected_dis", "4ff", "dm960", "lr_tune"]

  ^learning_rate: [0.0008, 0.0016, 0.0032, 0.0064] #dev
  # learning_rate: 0.001 #dev

  dmodel: 960
  dff: 3840
  dhead: 64 #dev
  n_steps: 31624 # 20T/ap

  dont_save_final_model: True

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"
