
parent: configs/projected_dis/4ff_large/common.yaml
md5_parent_hash: 0f5bbfd1acb29b5088f1f320eda7bea6
# time: 0-06:00:00
# time: 0-24:00:00
time: 2-00:00:00
n_gpus: 4
# n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "4ff", "compression", "pruning", "dm1152_1536", "1ot"] 
  # tags: ["projected_dis", "4ff", "compression", "pruning", "dm1152_1536", "tune_lr"]

  dmodel: 1152
  dff: 4608
  dhead: 64 #dev
  projected_dmodel: 1536
  projected_dff: 6144

  # ^learning_rate: [0.0005, 0.00025, 0.000125, 0.001]
  learning_rate: 0.00025 #best

  ^n_steps: [10179, 20358, 30537, 40716] # /net/storage/pr3/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-06-20_17-17-34
  # ^n_steps: [10179]

  pruning: random
  
  projected_distillation: True
  projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-05-31_20-00-21/None/674845/63559.pt # helios 20
  # projected_weights_path: /net/storage/pr3/plgrid/plggllmeffi/plgmstefaniak/checkpoints/def_1536_254236.pt # helios 80

  # projected_weights_path: /home/mstefaniak/checkpoints/dm_1536_63559.pt # entropy 20
  # projected_weights_path: /home/mstefaniak/llm_random_cemetery/PD_2025-06-13_16-04-41/None/52640/127118.pt # entropy 40

  # projected_weights_path: /home/ubuntu/mstefaniak/checkpoints/dm_1536_63559.pt # writer 20


  dont_save_final_model: False
  gradient_accumulation_steps: 2 #dev
  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"

