# @package _global_
hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  verbose:
      - __main__
      - model

git:
  remote_name: cemetery
  remote_url: git@github.com:llm-random/llm-random-cemetery.git

slurm:
  job-name: "nano"

venv_path: "venv/bin/activate"
experiment_prepare_venv_path: ${venv_path}