# @package _global_
metric_logger:
    _target_: model.MetricLoggerConfig
    type: "neptune"
    heavy_metrics_calculation_interval: 100
    project_name: "pmtest/llm-random"
    name: "nano"
    tags: ["nano"]