parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
interactive_debug: false
n_gpus: 1
time: "3-20:00:00"

params:
    harness_tasks: lambada,hellaswag,piqa,arc_easy,arc_challenge,winogrande
    # harness_tasks: arc_easy
    # harness_tasks: arc_easy
    load_weights_path: "/home/ubuntu/mot_checkpoints/base_32E_gradacc2/mehmtxpjeo.pt"
    batch_size: 32
    # harness_limit: 0.01
    # training:


    general_ff_layer_config: "vanilla,vanilla,vanilla,vanilla,vanilla,vanilla,cont_moe,cont_moe,cont_moe,cont_moe,cont_moe,cont_moe"

    #name
    name: mix_w_c4_eval
    tags: [mot, mix_w_c4]


    #mot
#    ^ff_mode: [cont_moe]
    group_size: 32
    n_experts: 32
    flop_matched: true
    sparsity_dim: 0
    temperature: 1.0


    #tuning
    learning_rate: 2e-4
    init_type: truncated_normal
    init_scale: 0.1
    weight_decay: 0.1


    #data
    n_steps: 150_000
    final_lr_step: 150_000
    dataset_type: c4


    #eval and logging
    log_gradients_and_weights: false
    decoding_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000


    #fsdp
    # fsdp_enabled: true
    # fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    # fsdp_selective_precision_modules: "AttentionMechanism"


    #throughput
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: false
    gradient_accumulation_steps: 2
    loss_checkpoint_chungs: 8