# Order should be from most specific to least specific
- name: "dgx"
  hosts: 
    - "login01"
    - "gpu01"

- name: "entropy"
  hosts: 
    - "asusgpu0"
    - "a100a"

- name: "athena"
  hosts: 
    - "t00*"