# @package _global_
cluster_name: "entropia"


trainer_factory:
  train_dataloader:
    dataset_path: "/storage_ssd_1/llm-random-data/train"

  eval_dataloader:
    dataset_path: "/storage_ssd_1/llm-random-data/validation"

slurm:
  partition: "h100"

cemetery_experiments_dir: "~/llmrandom_cemetery"